### ISSUE TITLE
Failed to load the text-pastry package

### ISSUE THREAD

**Issue by freemanoid** [seveibar/text-pastry#11]
Just updated to 0.190.0 and got this issue after atom has started.

**Atom Version**: 0.190.0
**System**: Mac OS X 10.10.3
**Thrown From**: [text-pastry](https://github.com/seveibar/text-pastry) package, v0.4.3

### Stack Trace

Failed to load the text-pastry package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/freeman/.atom/packages/text-pastry/lib/text-pastry-view.coffee:4:199)
    at /Users/freeman/.atom/packages/text-pastry/lib/text-pastry-view.coffee:9:5
    at Object.<anonymous> (/Users/freeman/.atom/packages/text-pastry/lib/text-pastry-view.coffee:94:5)
    at Object.<anonymous> (/Users/freeman/.atom/packages/text-pastry/lib/text-pastry-view.coffee:96:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "disabledPackages": [
      "rspec",
      "linter"
    ],
    "destroyEmptyPanes": false
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus, v2.8.0
capybara-snippets, v0.2.0
file-icons, v1.5.3
language-haml, v0.17.0
monokai, v0.13.0
rspec-snippets, v0.4.0
text-pastry, v0.4.3

# Dev
No dev packages
```

**Comment by kaushikgopal** [comment]
yup i updated to 1.0 and got the same issue

**Comment by alexbet** [comment]
+1

**Comment by seveibar** [comment]
fixed with #17, thanks for reporting!

**Comment by alexbet** [comment]
Not fixed on Atom 1.1.0. Getting the issue since I updated to 1.1.0.

**Comment by seveibar** [comment]
Thanks @alexbet, I'll take a look tonight

**Comment by seveibar** [comment]
it looks like this was due to an error when i published (woops) the package is now up to date.

@alexbet would you mind verifying the fix on your system (otherwise it may be a separate issue)

**Comment by alexbet** [comment]
I am not getting the error now, but there is now a different problem. When I try to use Text Pastry, the numbers are added to the very first line in the code and not where I put the cursors. The package is useless like this. Can you please look into why this may be happening? Thanks!

**Comment by seveibar** [comment]
Fixed with v0.6.1 seems a typo was accidentally introduced. Should be fixed, thanks again @alexbet!

**Comment by alexbet** [comment]
Awesome! Thanks @seveibar. :)
